name: Python hot

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Add conda to system path
      run: |
         curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py 
         python3 get-pip.py          
         pip3 install requests
         cd /home/runner/work/Hot/Hot
         bash github.sh
         
         
         
    - name: push
      run: |
          git config --global user.email "ad.china0731+cnmeeiagithub@gmail.com"
          git config --global user.name "cnmeeia"
          git add . 
          git commit -m "github action push"
          git push -f 
